# Site settings
title: Der Physics Jagger
author:
  name: Zinc
  email: lugwis1712@gmail.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
